# Generated by Django 4.1.5 on 2023-01-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('language', models.PositiveIntegerField(verbose_name='国語')),
                ('math', models.PositiveIntegerField(verbose_name='数学')),
                ('english', models.PositiveIntegerField(verbose_name='英語')),
            ],
        ),
    ]
